# site settings
title: Dan 
subtitle: Millward
email: millward123@outlook.com
description: Creative thinker. Passion for code and design.<br />Always building, always learning.
baseurl: "" # the subpath of your site, e.g. /blog
url: "dj2-millward.github.io" # the base hostname & protocol for your site
author:
# street_address: 1234 Somewhere Road
city: Teignmouth
state: Devon
#zip_code: 55555
country: United Kingdom
#phone: (716) 555-5555

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 4

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/dj2-millward
  GitLab:
  Google-Plus: 
  Instagram:
  LinkedIn: www.linkedin.com/in/djmillward 
  Twitter: 
  Facebook:
  Slack: 

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
